# Site Settings
locale: en-US # 网站语言，保持不变即可
title: "Jiawei Gu (顾佳伟)" # 这是你的网站标题，会显示在浏览器标签页和网站头部
name: "Jiawei Gu" # 你的名字
description: "MSc Student in Computer Science | Natural Language Processing & Multimodal AI" # 你的简介或格言
url: "https://你的GitHub用户名.github.io" # ⭐ 重要：把这里改成你的实际网站地址，例如 "https://jiaweigu.github.io"
repository: "你的GitHub用户名/你的GitHub用户名.github.io" # GitHub 仓库名称，例如 "jiaweigu/jiaweigu.github.io"
teaser: # 网站分享时的缩略图，留空或设置为默认图片路径
og_image: https://你的GitHub用户名.github.io/images/default-thumb.png # 社交媒体分享图片路径，替换为你的实际地址

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Minimal Mistakes 主题版本，如果你是 Fork 的，可以删除这行或保持不变
# 或者如果你是 Fork 的，通常不需要 remote_theme
# theme: minimal-mistakes-jekyll # 如果你 Fork 并重命名了，这行可能已存在，保持不变

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

kramdown:
  input: GFM
  hard_wrap: false # This is important for wrapping long sentences

analytics:
  provider: "google-gtag" # 或者 "google"
  google:
    tracking_id: "G-YOUR_TRACKING_ID" # ⭐ 如果你需要Google Analytics，请替换为你的跟踪ID。如果你不需要，可以删除 analytics 整个部分或注释掉。

# Site Author
author:
  name: "Jiawei Gu" # 你的名字
  avatar: "/assets/images/avatar.jpg" # ⭐ 你的头像图片路径，确保文件名和路径正确
  bio: "MSc student in Computer Science at Sun Yat-sen University." # 简短的个人介绍
  location: "Guangzhou, China" # 你的城市和国家
  email: "Kuvvius@gmail.com" # ⭐ 你的邮箱
  links: # 侧边栏的社交媒体链接和图标
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square" # 信封图标
      url: "mailto:Kuvvius@gmail.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square" # Google Scholar 图标
      url: "YOUR_GOOGLE_SCHOLAR_LINK" # ⭐ 替换为你的 Google Scholar 主页链接
    - label: "GitHub"
      icon: "fab fa-fw fa-github" # GitHub 图标
      url: "https://github.com/你的GitHub用户名" # ⭐ 替换为你的 GitHub 主页链接
    - label: "X" # Twitter 的新名称
      icon: "fab fa-fw fa-x-twitter" # X (Twitter) 图标
      url: "YOUR_TWITTER_LINK" # ⭐ 替换为你的 X (Twitter) 链接

# Social Media Integration (用于社交媒体分享时的预览)
twitter:
  username: "@你的Twitter用户名" # ⭐ 替换为你的 Twitter 用户名 (如果有)
  card: summary # 或 summary_large_image
  image: https://你的GitHub用户名.github.io/images/default-thumb.png # ⭐ 社交媒体分享图片路径，替换为你的实际地址
