# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
minimal_mistakes_skin    : "default" 

# Site Settings
locale                   : "en-US"
title                    : "Jiawei Gu (顾嘉炜)" 
title_separator          : "-"
name                     : "Jiawei Gu" 
description              : "MSc Student in Computer Science | Natural Language Processing & Multimodal AI"
url                      : "https://kuvvius.github.io/"
baseurl                  : # 保持空，GitHub Pages 不需要 baseurl
repository               : "Kuvvius/kuvvius.github.io"
teaser                   : # 保持空
logo                     : # 保持空
masthead_title           : # 保持空
breadcrumbs              : # 保持空
words_per_minute         : 200
enable_copy_code_button  : # 保持空
copyright                : "© 2025 Jiawei Gu."
copyright_url            : "https://kuvvius.github.io/" # ⭐ 已修改：版权链接指向网站主页


comments:
  provider               : # 保持空

# Social Sharing (用于社交媒体分享时的预览)
twitter:
  username               : "@YOUR_TWITTER_USERNAME" # ⭐ 替换：你的 Twitter 用户名 (如果有)。如果没有，可以删除这行。
facebook:
  username               : # 保持空
  app_id                 : # 保持空
  publisher              : # 保持空
og_image                 : "https://kuvvius.github.io/assets/images/default-thumb.png" # ⭐ 替换：社交媒体分享时显示的默认图片，替换为你的实际网站地址和图片路径。

# Social Profiles (高级结构化数据，保持默认或注释)
social:
  type                   : Person
  name                   : Jiawei Gu
  links: # 保持空或根据需要添加

# Analytics (网站分析)
analytics:
  provider               : "google-gtag" # 启用 Google Analytics Gtag
  google:
    tracking_id          : "G-YOUR_TRACKING_ID" # ⭐ 替换：你的 Google Analytics 跟踪 ID。如果你不需要分析，可以删除 analytics 整个部分或注释掉。
    anonymize_ip         : true

# Site Author (网站作者信息，显示在侧边栏或页面底部)
author:
  name             : "Jiawei Gu"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "MSc student in Computer Science at Sun Yat-sen University."
  location         : "Guangzhou, China"
  email            : "Kuvvius@gmail.com"
  links: # 侧边栏的社交媒体链接和图标
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square" # Font Awesome 邮箱图标
      url: "mailto:Kuvvius@gmail.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square" # Academicons Google Scholar 图标
      url: "https://scholar.google.com/citations?user=7p8yEHAAAAAJ&hl=En"
    - label: "GitHub"
      icon: "fab fa-fw fa-github" # Font Awesome GitHub 图标
      url: "https://github.com/Kuvvius"
    - label: "X"
      icon: "fab fa-fw fa-x-twitter" # Font Awesome X (Twitter) 图标
      url: "https://x.com/Kuvvius"

# Site Footer (网站底部)
footer:
  links:
  since: "2025"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: # 保持空

# Pagination with jekyll-paginate (禁用分页，除非你需要博客文章)
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2 (禁用分页)
pagination:
  enabled: false # 设置为 false 禁用
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins (主题所需插件)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme # 如果你是 Fork 的，这行通常不需要，或者根据你的主题版本自动添加

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme # 同上，如果需要

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults (默认设置，确保主页正确渲染)
defaults:
  # _posts 默认设置
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false # 默认为文章禁用评论
      share: true
      related: true
  # _pages (例如你的 index.md 主页) 默认设置
  - scope:
      path: ""
      type: pages
    values:
      layout: page # 确保主页使用 page 布局
      permalink: / # 确保主页的固定链接是根目录
      author_profile: false # ⭐ 已修改：禁用 Minimal Mistakes 自带的作者简介，以便你手动添加
      comments: false # 默认为页面禁用评论
      share: false # 默认不显示分享按钮